# ----------------------------
# Makefile Options
# ----------------------------

NAME = ENGINE
ICON = icon.png
DESCRIPTION = "A simple lightweight 3D engine for the TI84 Plus CE"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
